# Generated by Django 4.1.7 on 2023-03-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_alter_libro_autores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='visitar',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
